libc_a_SOURCES += \
	syscalls/sysclose.c \
	syscalls/sysfcntl.c \
	syscalls/sysfstat.c \
	syscalls/sysgetentropy.c \
	syscalls/sysgetpid.c \
	syscalls/sysgettod.c \
	syscalls/sysisatty.c \
	syscalls/syskill.c \
	syscalls/syslink.c \
	syscalls/syslseek.c \
	syscalls/sysopen.c \
	syscalls/sysread.c \
	syscalls/syssbrk.c \
	syscalls/sysstat.c \
	syscalls/systimes.c \
	syscalls/sysunlink.c \
	syscalls/syswrite.c
