libc_a_SOURCES += \
	sys/syscalls.c \
	sys/fdtable/isatty.c \
	sys/fdtable/close.c \
	sys/fdtable/fdtable.c \
	sys/fdtable/ftruncate.c \
	sys/fdtable/write.c \
	sys/fdtable/read.c \
	sys/fdtable/open.c \
	sys/fdtable/lseek.c \
	sys/fdtable/fstat.c \
	sys/fdtable/stat.c \
	sys/fdtable/stat_common.c
