libc_a_SOURCES += \
	search/bsearch.c \
	search/ndbm.c \
	search/qsort.c \
	search/hash.c \
	search/hash_bigkey.c \
	search/hash_buf.c \
	search/hash_func.c \
	search/hash_log2.c \
	search/hash_page.c \
	search/hcreate.c \
	search/hcreate_r.c \
	search/tdelete.c \
	search/tdestroy.c \
	search/tfind.c \
	search/tsearch.c \
	search/twalk.c \
	search/bsd_qsort_r.c \
	search/qsort_r.c
