libc_a_SOURCES += \
	argz/argz_add.c \
	argz/argz_add_sep.c \
	argz/argz_append.c \
	argz/argz_count.c \
	argz/argz_create.c \
	argz/argz_create_sep.c \
	argz/argz_delete.c \
	argz/argz_extract.c \
	argz/argz_insert.c \
	argz/argz_next.c \
	argz/argz_replace.c \
	argz/argz_stringify.c \
	argz/buf_findstr.c \
	argz/envz_entry.c \
	argz/envz_get.c \
	argz/envz_add.c \
	argz/envz_remove.c \
	argz/envz_merge.c \
	argz/envz_strip.c
