libc_a_SOURCES += \
	locale/locale.c \
	locale/localeconv.c \
	locale/duplocale.c \
	locale/freelocale.c \
	locale/getlocalename_l.c \
	locale/lctype.c \
	locale/lmessages.c \
	locale/lnumeric.c \
	locale/lmonetary.c \
	locale/newlocale.c \
	locale/nl_langinfo.c \
	locale/timelocal.c \
	locale/uselocale.c
