libc_a_SOURCES += \
	time/asctime.c \
	time/asctime_r.c \
	time/clock.c \
	time/ctime.c \
	time/ctime_r.c \
	time/difftime.c \
	time/gettzinfo.c \
	time/gmtime.c \
	time/gmtime_r.c \
	time/lcltime.c \
	time/lcltime_r.c \
	time/mktime.c \
	time/month_lengths.c \
	time/strftime.c   \
	time/strptime.c \
	time/time.c \
	time/tzcalc_limits.c \
	time/tzlock.c \
	time/tzset.c \
	time/tzset_r.c \
	time/tzvars.c \
	time/wcsftime.c
