libc_a_SOURCES += \
	reent/closer.c \
	reent/reent.c \
	reent/impure.c \
	reent/fcntlr.c \
	reent/fstatr.c \
	reent/getentropyr.c \
	reent/getreent.c \
	reent/gettimeofdayr.c \
	reent/isattyr.c \
	reent/linkr.c \
	reent/lseekr.c \
	reent/mkdirr.c \
	reent/openr.c \
	reent/readr.c \
	reent/renamer.c \
	reent/signalr.c \
	reent/sbrkr.c \
	reent/statr.c \
	reent/timesr.c \
	reent/unlinkr.c \
	reent/writer.c
